networks:
  aptestnet:
    name: aptestnet

services:
  tester:
    build:
      context: ../tester/deploy
      dockerfile: Dockerfile
      # no_cache: true
    image: sergiunb/aptester
    container_name: aptester
    volumes:
      - "../tester/notebooks:/home/jovyan/work"
    networks:
      - aptestnet
    ports:
      - "8888:8888"
    command: ["bash", "-c",
              "jupyter notebook --ip 0.0.0.0 --allow-root --no-browser --NotebookApp.token=''"]

  fastapianalytics:
    build:
      context: ../fastapi-analytics/deploy
      dockerfile: Dockerfile
      # no_cache: true
    working_dir: /home/app
    image: sergiunb/fastapianalytics
    container_name: fastapianalytics
    volumes:
      - "../fastapi-analytics/src:/home/app"
    networks:
      - aptestnet
    ports:
      - 3012:5000
    
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
