networks:
  aptestnet:
    name: aptestnet

services:
  tester:
    build:
      context: ../tester/deploy
      dockerfile: Dockerfile
      # no_cache: true
    image: sergiunb/aptester
    container_name: aptester
    volumes:
      - "../tester/notebooks:/home/jovyan/work"
    networks:
      - aptestnet
    ports:
      - "8888:8888"
    command: ["bash", "-c",
              "jupyter notebook --ip 0.0.0.0 --allow-root --no-browser --NotebookApp.token=''"]

  fastapianalytics:
    build:
      context: ../fastapi-analytics/deploy
      dockerfile: Dockerfile
      # no_cache: true
    working_dir: /home/app
    image: sergiunb/fastapianalytics
    container_name: fastapianalytics
    environment:
    # https://www.uvicorn.org/#command-line-options
      - UVICORN_APP=app:app
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=5000
      - UVICORN_WORKERS=1
      - UVICORN_LOG_LEVEL=trace
    volumes:
      - "../fastapi-analytics/src:/home/app"
    networks:
      - aptestnet
    ports:
      - 3012:5000
    
    command: ["uvicorn", "--reload"]
    # command: ["uvicorn"]

  flask1xanalytics:
    build:
      context: ../flask-analytics/deploy
      dockerfile: Dockerfile
      # no_cache: true
    working_dir: /home/app
    image: sergiunb/flaskanalytics
    container_name: flask1xanalytics
    environment:
      - GUNICORN_EXPOSED_ON=0.0.0.0:5000
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - "../flask-analytics/src:/home/app"
    networks:
      - aptestnet
    ports:
      - 3013:5000
    
    command: ["gunicorn", "-c", "gunicorn_1x_config.py", "app:app"]

  flask2xanalytics:
    build:
      context: ../flask-analytics/deploy
      dockerfile: Dockerfile
      # no_cache: true
    working_dir: /home/app
    image: sergiunb/flaskanalytics
    container_name: flask2xanalytics
    environment:
      - GUNICORN_EXPOSED_ON=0.0.0.0:5000
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    volumes:
      - "../flask-analytics/src:/home/app"
    networks:
      - aptestnet
    ports:
      - 3014:5000
    
    command: ["gunicorn", "-c", "gunicorn_2x_config.py", "app:app"]
